#!/bin/sh

SRC_THEME=/v/t
SRC_ARTICLES=/v/a
THEME_HEAD=${SRC_THEME}/README.txt
GIT_THEME=/tmp/danmaq.jekyll

cd /tmp
if [ -z "`ls ${SRC_THEME}`" -a `head -n 1 ${THEME_HEAD}` | grep 'Theme' ]; then
  mkdir -p ${GIT_THEME}
  cp -r /v/t/* ${GIT_THEME}/
else
  git clone git@github.com:danmaq/danmaq.jekyll.git
fi
# todo: テーマの適用


cp -r /v/a/_posts /srv/jekyll/
cp -r /v/a/root/* /srv/jekyll/
rm -rf /srv/jekyll/_site/*
cd /srv/jekyll

# ビルド！
jekyll s
