#!/bin/sh

if [ `which docker | wc -l` -eq 0 ]; then
  echo 'Docker service and client are required to run this setup.'
  exit 1
fi

mkdir -p tmp
mkdir -p _site

PJHOME=$(cd $(dirname $0)/..; pwd)

# ---- SET VOL1 ----
[ $# -ge 1 ] && VTHEME=$1 || VTHEME=${PJHOME}/tmp
VOL1=${VTHEME}:/v/t:ro

# ---- SET VOL2 ----
VOL2=${PJHOME}:/v/a:ro

# ---- SET VOL3 ----
VOL3=${PJHOME}_site:/srv/jekyll/_site

# ---- SET VOL4 ----
VOL4=${HOME}/.ssh/id_rsa:/root/.ssh/id_rsa:ro

CONTAINER=jekyll
IMAGE=danmaq/jekyll-git-redcarpet:github-pages
GIT_NAME='Jekyll bot by Shuhei Nomura'
GIT_EMAIL='info@danmaq.com'
LOOP='mkdir /root/.ssh;while true; do sleep 1; done'
docker run -d -p 4000:4000 -v ${VOL1} -v ${VOL2} -v ${VOL3} -e GIT_NAME="${GIT_NAME}" -e GIT_EMAIL="${GIT_EMAIL}" --name ${CONTAINER} ${IMAGE} sh -c "${LOOP}"

IP=`docker-machine ip docker`
printf "Please open via browser: \e[1;4mhttp://${IP}:4000\e[m\n"
docker exec -it ${CONTAINER} /v/a/test/incontainer
#docker exec -it ${CONTAINER} ash
docker rm -f ${CONTAINER}
